### ISSUE TITLE
Code convertToBinary method in PacketAnalyzer.py

### ISSUE THREAD

**Issue by FMock** [BenSieben/EntropyAnalysis#10]
This method takes the list of strings which are the filtered packets captures and turns the ASCII into their binary form. A good starting point might be to first convert each character into it's ascii value using python's ord() function:
The result of ord('A') is 65.

**Comment by BenSieben** [comment]
I have got a working version of the convertToBinary method in PacketAnalyzer.py up on the master branch (from two days ago). Any changes needed will be minimal, so this issue is resolved.
